server:
  port: 3344

spring:
  application:
    name:  shinley-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:shinley/shinley-config-repo.git

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false