server:
  port: 3366

spring:
  profiles:
    active: test
  application:
    name: shinley-feign-provider

# 当不注册到eureka上时，如下配置可以避免启动报错
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#eureka:
#    client:
#        service-url:
#            defaultZone: http://localhost:9000/eureka       # eureka服务
#    instance:
#        instance-id: shinley-feign-provider   # 修改注册Id
#        prefer-ip-address: true               # 访问路径可以显示IP